In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [4]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [7]:
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [10]:
np.random.random((3, 3))

array([[ 0.26133471,  0.85631972,  0.7136607 ],
       [ 0.40156905,  0.64431592,  0.86984176],
       [ 0.24940608,  0.25339024,  0.5616706 ]])

In [11]:
np.random.normal(0, 1, (3, 3))  # mean=0, std=1

array([[-1.07082472,  0.25085226,  0.71106796],
       [ 0.28614717, -2.36646044, -1.24515756],
       [ 0.42160226, -0.32074628, -0.41466472]])

In [12]:
np.random.randint(0, 10, (3, 3))  # [0,10)

array([[6, 8, 8],
       [7, 9, 1],
       [6, 8, 6]])

In [13]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
np.empty(3)  # no value init, values will be whatever happens to already exist at that memory location

array([ 1.,  1.,  1.])

In [17]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

('x3 ndim: ', 3)
('x3 shape:', (3, 4, 5))
('x3 size: ', 60)
('dtype:', dtype('int64'))
('itemsize:', 8, 'bytes')
('nbytes:', 480, 'bytes')


In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [20]:
x1[0], x1[3], x1[-1], x1[-2]

(5, 3, 9, 7)

In [21]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [22]:
x2[0, 0], x2[2, 0], x2[2, -1]

(3, 1, 7)

In [23]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [24]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[:5]

array([0, 1, 2, 3, 4])

In [26]:
x[5:]

array([5, 6, 7, 8, 9])

In [27]:
x[2:5]

array([2, 3, 4])

In [28]:
x[::2]

array([0, 2, 4, 6, 8])

In [29]:
x[1::2]

array([1, 3, 5, 7, 9])

In [30]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
x[5::-2]

array([5, 3, 1])

In [32]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [33]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [35]:
x2[:2, ::2]

array([[12,  2],
       [ 7,  8]])

In [36]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [37]:
x2[:, 0]

array([12,  7,  1])

In [38]:
x2[0]  # == x2[0, :]

array([12,  5,  2,  4])

In [39]:
x2_sub = x2[:2, :2]  # view
x2_sub

array([[12,  5],
       [ 7,  6]])

In [40]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [41]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [42]:
x2_sub_copy = x2[:2, :2].copy()  # copy
x2_sub_copy[0, 0] = 42
print x2_sub_copy
print x2

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [43]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
x = np.array([1, 2, 3])
print x.shape
print x[:, np.newaxis].shape
print x[np.newaxis, :].shape
print x.reshape(-1, 1).shape
print x.reshape(1, -1).shape

(3,)
(3, 1)
(1, 3)
(3, 1)
(1, 3)


In [45]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print np.concatenate([x, y])
z = [9, 9, 9]
print np.concatenate([x, y, z])

[1 2 3 3 2 1]
[1 2 3 3 2 1 9 9 9]


In [46]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print np.concatenate([grid, grid])
print np.concatenate([grid, grid], axis=1)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [47]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [48]:
y = np.array([[99],
              [99]])
# horizontally stack the arrays
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [50]:
x=[1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))


In [52]:
a, b = np.vsplit(np.arange(16).reshape((4, 4)), [2])
print a
print b

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [53]:
a, b = np.hsplit(np.arange(16).reshape((4, 4)), [2])
print a
print b

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [54]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 3: 336 ms per loop


In [55]:
%timeit (1.0 / big_array)

100 loops, best of 3: 4.11 ms per loop


Operator Equivalent ufunc
+ np.add
- np.subtract
- np.negative
* np.multiply
/ np.divide
// np.floor_divide \*\* np.power
% np.mod

In [57]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)
print('-(0.5*x + 1) ** 2 =  ', -(0.5*x + 1) ** 2)

('x =', array([0, 1, 2, 3]))
('x + 5 =', array([5, 6, 7, 8]))
('x - 5 =', array([-5, -4, -3, -2]))
('x * 2 =', array([0, 2, 4, 6]))
('x / 2 =', array([0, 0, 1, 1]))
('x // 2 =', array([0, 0, 1, 1]))
('-x = ', array([ 0, -1, -2, -3]))
('x ** 2 = ', array([0, 1, 4, 9]))
('x % 2 = ', array([0, 1, 0, 1]))
('-(0.5*x + 1) ** 2 =  ', array([-1.  , -2.25, -4.  , -6.25]))


In [58]:
np.absolute is np.abs

True

In [59]:
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

('theta = ', array([ 0.        ,  1.57079633,  3.14159265]))
('sin(theta) = ', array([  0.00000000e+00,   1.00000000e+00,   1.22464680e-16]))
('cos(theta) = ', array([  1.00000000e+00,   6.12323400e-17,  -1.00000000e+00]))
('tan(theta) = ', array([  0.00000000e+00,   1.63312394e+16,  -1.22464680e-16]))
('x = ', [-1, 0, 1])
('arcsin(x) = ', array([-1.57079633,  0.        ,  1.57079633]))
('arccos(x) = ', array([ 3.14159265,  1.57079633,  0.        ]))
('arctan(x) = ', array([-0.78539816,  0.        ,  0.78539816]))


In [60]:
x = [1, 2, 3]
print("x =", x)
print("e^x =",np.exp(x))
print("2^x =",np.exp2(x))
print("3^x =",np.power(3,x))
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

('x =', [1, 2, 3])
('e^x =', array([  2.71828183,   7.3890561 ,  20.08553692]))
('2^x =', array([ 2.,  4.,  8.]))
('3^x =', array([ 3,  9, 27]))
('x =', [1, 2, 4, 10])
('ln(x) =', array([ 0.        ,  0.69314718,  1.38629436,  2.30258509]))
('log2(x) =', array([ 0.        ,  1.        ,  2.        ,  3.32192809]))
('log10(x) =', array([ 0.        ,  0.30103   ,  0.60205999,  1.        ]))
('exp(x) - 1 =', array([ 0.        ,  0.0010005 ,  0.01005017,  0.10517092]))
('log(1 + x) =', array([ 0.        ,  0.0009995 ,  0.00995033,  0.09531018]))


In [61]:
from scipy import special
# Gamma functions (generalized factorials) and related functions
x=[1,5,10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))
# Error function (integral of Gaussian) # its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

('gamma(x) =', array([  1.00000000e+00,   2.40000000e+01,   3.62880000e+05]))
('ln|gamma(x)| =', array([  0.        ,   3.17805383,  12.80182748]))
('beta(x, 2) =', array([ 0.5       ,  0.03333333,  0.00909091]))
('erf(x) =', array([ 0.        ,  0.32862676,  0.67780119,  0.84270079]))
('erfc(x) =', array([ 1.        ,  0.67137324,  0.32219881,  0.15729921]))
('erfinv(x) =', array([ 0.        ,  0.27246271,  0.73286908,         inf]))


In [62]:
# For all ufuncs, you can do this using the out argument of the function:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[  0.  10.  20.  30.  40.]


In [63]:
# for very large arrays the memory savings from careful use of the out argument can be significant
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


In [65]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 77.1 ms per loop
1000 loops, best of 3: 353 µs per loop


In [66]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 3: 62.8 ms per loop
1000 loops, best of 3: 295 µs per loop
