In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
plt.style.use('ggplot')

In [8]:
# handle bottom-up data
a = np.array([
        [0, 1],
        [1, 1]
    ])
eigval, eigvecs = np.linalg.eig(a)

In [9]:
eigval

array([-0.61803399,  1.61803399])

In [10]:
eigvecs

array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]])

In [11]:
2/-0.85065081

-2.351141004615043

In [12]:
-2.351141004615043*0.52573111

-1.2360679701227817

In [14]:
1+(5**0.5)

3.23606797749979

In [15]:
1-(5**0.5)

-1.2360679774997898

In [17]:
np.allclose(np.dot(a, eigvecs[:, 0]), eigval[0]*eigvecs[:, 0])

True

In [19]:
np.linalg.inv(eigvecs)

array([[-0.85065081,  0.52573111],
       [-0.52573111, -0.85065081]])